# Generated by Django 5.0.6 on 2024-09-01 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encadreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('specialite', models.CharField(max_length=20)),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('date_de_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_de_stage', models.CharField(max_length=20)),
                ('sujet', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_de_debut', models.DateField()),
                ('date_de_fin', models.DateField()),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('date_de_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('rapport', 'Rapport de Stage'), ('presentation', 'Presentations'), ('convention', 'Convention de Stage')], max_length=20)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('ecole', models.CharField(blank=True, max_length=20)),
                ('abbreviation', models.CharField(blank=True, max_length=10)),
                ('filiere', models.CharField(blank=True, max_length=20)),
                ('niveau', models.CharField(blank=True, max_length=20)),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('date_de_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stagiaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projet_realise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='projets/')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('date_de_modification', models.DateTimeField(auto_now=True)),
                ('encadreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaires.encadreur')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaires.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('next_steps', models.TextField(blank=True)),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaires.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_candidature', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('accepté', 'Accepté'), ('refusé', 'Refusé')], default='en attente', max_length=20)),
                ('encadreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stagiaires.encadreur')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaires.stage')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaires.stagiaire')),
            ],
        ),
    ]
